import { BibleReadingPlan, Passage } from '../types/bible.types';

function p(bookCode: string, bookName: string, chapter: number, startVerse?: number, endVerse?: number): Passage {
  const display = startVerse
    ? endVerse
      ? `${bookName} ${chapter}:${startVerse}-${endVerse}`
      : `${bookName} ${chapter}:${startVerse}`
    : `${bookName} ${chapter}`;
  const apiBase = bookName.toLowerCase().replace(/\s/g, '+');
  const apiQuery = startVerse
    ? endVerse
      ? `${apiBase}+${chapter}:${startVerse}-${endVerse}`
      : `${apiBase}+${chapter}:${startVerse}`
    : `${apiBase}+${chapter}`;
  return {
    id: startVerse ? `${bookCode}.${chapter}.${startVerse}` : `${bookCode}.${chapter}`,
    bookCode,
    bookName,
    chapter,
    startVerse,
    endVerse,
    displayText: display,
    apiQuery,
  };
}

// M'Cheyne One-Year Plan: OT ch1, NT ch1, OT ch2 (or Psalms), NT ch2
// Covers OT once, NT + Psalms twice
export const MCHEYNE_PLAN: BibleReadingPlan = {
  id: 'mcheyne-one-year',
  name: "M'Cheyne One-Year",
  description: "The classic 19th-century plan by Robert Murray M'Cheyne. Read the NT and Psalms twice, the rest of the OT once — 4 passages daily.",
  totalDays: 365,
  estimatedMinutesPerDay: 20,
  dailyReadings: [
    { day: 1, passages: [p('GEN','Genesis',1), p('MAT','Matthew',1), p('EZR','Ezra',1), p('ACT','Acts',1)] },
    { day: 2, passages: [p('GEN','Genesis',2), p('MAT','Matthew',2), p('EZR','Ezra',2), p('ACT','Acts',2)] },
    { day: 3, passages: [p('GEN','Genesis',3), p('MAT','Matthew',3), p('EZR','Ezra',3), p('ACT','Acts',3)] },
    { day: 4, passages: [p('GEN','Genesis',4), p('MAT','Matthew',4), p('EZR','Ezra',4), p('ACT','Acts',4)] },
    { day: 5, passages: [p('GEN','Genesis',5), p('MAT','Matthew',5), p('EZR','Ezra',5), p('ACT','Acts',5)] },
    { day: 6, passages: [p('GEN','Genesis',6), p('MAT','Matthew',6), p('EZR','Ezra',6), p('ACT','Acts',6)] },
    { day: 7, passages: [p('GEN','Genesis',7), p('MAT','Matthew',7), p('EZR','Ezra',7), p('ACT','Acts',7)] },
    { day: 8, passages: [p('GEN','Genesis',8), p('MAT','Matthew',8), p('EZR','Ezra',8), p('ACT','Acts',8)] },
    { day: 9, passages: [p('GEN','Genesis',9), p('MAT','Matthew',9), p('EZR','Ezra',9), p('ACT','Acts',9)] },
    { day: 10, passages: [p('GEN','Genesis',10), p('MAT','Matthew',10), p('EZR','Ezra',10), p('ACT','Acts',10)] },
    { day: 11, passages: [p('GEN','Genesis',11), p('MAT','Matthew',11), p('NEH','Nehemiah',1), p('ACT','Acts',11)] },
    { day: 12, passages: [p('GEN','Genesis',12), p('MAT','Matthew',12), p('NEH','Nehemiah',2), p('ACT','Acts',12)] },
    { day: 13, passages: [p('GEN','Genesis',13), p('MAT','Matthew',13), p('NEH','Nehemiah',3), p('ACT','Acts',13)] },
    { day: 14, passages: [p('GEN','Genesis',14), p('MAT','Matthew',14), p('NEH','Nehemiah',4), p('ACT','Acts',14)] },
    { day: 15, passages: [p('GEN','Genesis',15), p('MAT','Matthew',15), p('NEH','Nehemiah',5), p('ACT','Acts',15)] },
    { day: 16, passages: [p('GEN','Genesis',16), p('MAT','Matthew',16), p('NEH','Nehemiah',6), p('ACT','Acts',16)] },
    { day: 17, passages: [p('GEN','Genesis',17), p('MAT','Matthew',17), p('NEH','Nehemiah',7), p('ACT','Acts',17)] },
    { day: 18, passages: [p('GEN','Genesis',18), p('MAT','Matthew',18), p('NEH','Nehemiah',8), p('ACT','Acts',18)] },
    { day: 19, passages: [p('GEN','Genesis',19), p('MAT','Matthew',19), p('NEH','Nehemiah',9), p('ACT','Acts',19)] },
    { day: 20, passages: [p('GEN','Genesis',20), p('MAT','Matthew',20), p('NEH','Nehemiah',10), p('ACT','Acts',20)] },
    { day: 21, passages: [p('GEN','Genesis',21), p('MAT','Matthew',21), p('NEH','Nehemiah',11), p('ACT','Acts',21)] },
    { day: 22, passages: [p('GEN','Genesis',22), p('MAT','Matthew',22), p('NEH','Nehemiah',12), p('ACT','Acts',22)] },
    { day: 23, passages: [p('GEN','Genesis',23), p('MAT','Matthew',23), p('NEH','Nehemiah',13), p('ACT','Acts',23)] },
    { day: 24, passages: [p('GEN','Genesis',24), p('MAT','Matthew',24), p('EST','Esther',1), p('ACT','Acts',24)] },
    { day: 25, passages: [p('GEN','Genesis',25), p('MAT','Matthew',25), p('EST','Esther',2), p('ACT','Acts',25)] },
    { day: 26, passages: [p('GEN','Genesis',26), p('MAT','Matthew',26), p('EST','Esther',3), p('ACT','Acts',26)] },
    { day: 27, passages: [p('GEN','Genesis',27), p('MAT','Matthew',27), p('EST','Esther',4), p('ACT','Acts',27)] },
    { day: 28, passages: [p('GEN','Genesis',28), p('MAT','Matthew',28), p('EST','Esther',5), p('ACT','Acts',28)] },
    { day: 29, passages: [p('GEN','Genesis',29), p('MRK','Mark',1), p('EST','Esther',6), p('ROM','Romans',1)] },
    { day: 30, passages: [p('GEN','Genesis',30), p('MRK','Mark',2), p('EST','Esther',7), p('ROM','Romans',2)] },
    { day: 31, passages: [p('GEN','Genesis',31), p('MRK','Mark',3), p('EST','Esther',8), p('ROM','Romans',3)] },
    { day: 32, passages: [p('GEN','Genesis',32), p('MRK','Mark',4), p('EST','Esther',9), p('ROM','Romans',4)] },
    { day: 33, passages: [p('GEN','Genesis',33), p('MRK','Mark',5), p('EST','Esther',10), p('ROM','Romans',5)] },
    { day: 34, passages: [p('GEN','Genesis',34), p('MRK','Mark',6), p('JOB','Job',1), p('ROM','Romans',6)] },
    { day: 35, passages: [p('GEN','Genesis',35), p('MRK','Mark',7), p('JOB','Job',2), p('ROM','Romans',7)] },
    { day: 36, passages: [p('GEN','Genesis',36), p('MRK','Mark',8), p('JOB','Job',3), p('ROM','Romans',8)] },
    { day: 37, passages: [p('GEN','Genesis',37), p('MRK','Mark',9), p('JOB','Job',4), p('ROM','Romans',9)] },
    { day: 38, passages: [p('GEN','Genesis',38), p('MRK','Mark',10), p('JOB','Job',5), p('ROM','Romans',10)] },
    { day: 39, passages: [p('GEN','Genesis',39), p('MRK','Mark',11), p('JOB','Job',6), p('ROM','Romans',11)] },
    { day: 40, passages: [p('GEN','Genesis',40), p('MRK','Mark',12), p('JOB','Job',7), p('ROM','Romans',12)] },
    { day: 41, passages: [p('GEN','Genesis',41), p('MRK','Mark',13), p('JOB','Job',8), p('ROM','Romans',13)] },
    { day: 42, passages: [p('GEN','Genesis',42), p('MRK','Mark',14), p('JOB','Job',9), p('ROM','Romans',14)] },
    { day: 43, passages: [p('GEN','Genesis',43), p('MRK','Mark',15), p('JOB','Job',10), p('ROM','Romans',15)] },
    { day: 44, passages: [p('GEN','Genesis',44), p('MRK','Mark',16), p('JOB','Job',11), p('ROM','Romans',16)] },
    { day: 45, passages: [p('GEN','Genesis',45), p('LUK','Luke',1), p('JOB','Job',12), p('1CO','1 Corinthians',1)] },
    { day: 46, passages: [p('GEN','Genesis',46), p('LUK','Luke',2), p('JOB','Job',13), p('1CO','1 Corinthians',2)] },
    { day: 47, passages: [p('GEN','Genesis',47), p('LUK','Luke',3), p('JOB','Job',14), p('1CO','1 Corinthians',3)] },
    { day: 48, passages: [p('GEN','Genesis',48), p('LUK','Luke',4), p('JOB','Job',15), p('1CO','1 Corinthians',4)] },
    { day: 49, passages: [p('GEN','Genesis',49), p('LUK','Luke',5), p('JOB','Job',16), p('1CO','1 Corinthians',5)] },
    { day: 50, passages: [p('GEN','Genesis',50), p('LUK','Luke',6), p('JOB','Job',17), p('1CO','1 Corinthians',6)] },
    // Continue through Exodus, etc. - abbreviated for space
    // Full 365-day plan continues the pattern:
    { day: 51, passages: [p('EXO','Exodus',1), p('LUK','Luke',7), p('JOB','Job',18), p('1CO','1 Corinthians',7)] },
    { day: 52, passages: [p('EXO','Exodus',2), p('LUK','Luke',8), p('JOB','Job',19), p('1CO','1 Corinthians',8)] },
    { day: 53, passages: [p('EXO','Exodus',3), p('LUK','Luke',9), p('JOB','Job',20), p('1CO','1 Corinthians',9)] },
    { day: 54, passages: [p('EXO','Exodus',4), p('LUK','Luke',10), p('JOB','Job',21), p('1CO','1 Corinthians',10)] },
    { day: 55, passages: [p('EXO','Exodus',5), p('LUK','Luke',11), p('JOB','Job',22), p('1CO','1 Corinthians',11)] },
    { day: 56, passages: [p('EXO','Exodus',6), p('LUK','Luke',12), p('JOB','Job',23), p('1CO','1 Corinthians',12)] },
    { day: 57, passages: [p('EXO','Exodus',7), p('LUK','Luke',13), p('JOB','Job',24), p('1CO','1 Corinthians',13)] },
    { day: 58, passages: [p('EXO','Exodus',8), p('LUK','Luke',14), p('JOB','Job',25), p('1CO','1 Corinthians',14)] },
    { day: 59, passages: [p('EXO','Exodus',9), p('LUK','Luke',15), p('JOB','Job',26), p('1CO','1 Corinthians',15)] },
    { day: 60, passages: [p('EXO','Exodus',10), p('LUK','Luke',16), p('JOB','Job',27), p('1CO','1 Corinthians',16)] },
    { day: 61, passages: [p('EXO','Exodus',11), p('LUK','Luke',17), p('JOB','Job',28), p('2CO','2 Corinthians',1)] },
    { day: 62, passages: [p('EXO','Exodus',12), p('LUK','Luke',18), p('JOB','Job',29), p('2CO','2 Corinthians',2)] },
    { day: 63, passages: [p('EXO','Exodus',13), p('LUK','Luke',19), p('JOB','Job',30), p('2CO','2 Corinthians',3)] },
    { day: 64, passages: [p('EXO','Exodus',14), p('LUK','Luke',20), p('JOB','Job',31), p('2CO','2 Corinthians',4)] },
    { day: 65, passages: [p('EXO','Exodus',15), p('LUK','Luke',21), p('JOB','Job',32), p('2CO','2 Corinthians',5)] },
    { day: 66, passages: [p('EXO','Exodus',16), p('LUK','Luke',22), p('JOB','Job',33), p('2CO','2 Corinthians',6)] },
    { day: 67, passages: [p('EXO','Exodus',17), p('LUK','Luke',23), p('JOB','Job',34), p('2CO','2 Corinthians',7)] },
    { day: 68, passages: [p('EXO','Exodus',18), p('LUK','Luke',24), p('JOB','Job',35), p('2CO','2 Corinthians',8)] },
    { day: 69, passages: [p('EXO','Exodus',19), p('JHN','John',1), p('JOB','Job',36), p('2CO','2 Corinthians',9)] },
    { day: 70, passages: [p('EXO','Exodus',20), p('JHN','John',2), p('JOB','Job',37), p('2CO','2 Corinthians',10)] },
    { day: 71, passages: [p('EXO','Exodus',21), p('JHN','John',3), p('JOB','Job',38), p('2CO','2 Corinthians',11)] },
    { day: 72, passages: [p('EXO','Exodus',22), p('JHN','John',4), p('JOB','Job',39), p('2CO','2 Corinthians',12)] },
    { day: 73, passages: [p('EXO','Exodus',23), p('JHN','John',5), p('JOB','Job',40), p('2CO','2 Corinthians',13)] },
    { day: 74, passages: [p('EXO','Exodus',24), p('JHN','John',6), p('JOB','Job',41), p('GAL','Galatians',1)] },
    { day: 75, passages: [p('EXO','Exodus',25), p('JHN','John',7), p('JOB','Job',42), p('GAL','Galatians',2)] },
    { day: 76, passages: [p('EXO','Exodus',26), p('JHN','John',8), p('PSA','Psalms',1), p('GAL','Galatians',3)] },
    { day: 77, passages: [p('EXO','Exodus',27), p('JHN','John',9), p('PSA','Psalms',2), p('GAL','Galatians',4)] },
    { day: 78, passages: [p('EXO','Exodus',28), p('JHN','John',10), p('PSA','Psalms',3), p('GAL','Galatians',5)] },
    { day: 79, passages: [p('EXO','Exodus',29), p('JHN','John',11), p('PSA','Psalms',4), p('GAL','Galatians',6)] },
    { day: 80, passages: [p('EXO','Exodus',30), p('JHN','John',12), p('PSA','Psalms',5), p('EPH','Ephesians',1)] },
    { day: 81, passages: [p('EXO','Exodus',31), p('JHN','John',13), p('PSA','Psalms',6), p('EPH','Ephesians',2)] },
    { day: 82, passages: [p('EXO','Exodus',32), p('JHN','John',14), p('PSA','Psalms',7), p('EPH','Ephesians',3)] },
    { day: 83, passages: [p('EXO','Exodus',33), p('JHN','John',15), p('PSA','Psalms',8), p('EPH','Ephesians',4)] },
    { day: 84, passages: [p('EXO','Exodus',34), p('JHN','John',16), p('PSA','Psalms',9), p('EPH','Ephesians',5)] },
    { day: 85, passages: [p('EXO','Exodus',35), p('JHN','John',17), p('PSA','Psalms',10), p('EPH','Ephesians',6)] },
    { day: 86, passages: [p('EXO','Exodus',36), p('JHN','John',18), p('PSA','Psalms',11), p('PHP','Philippians',1)] },
    { day: 87, passages: [p('EXO','Exodus',37), p('JHN','John',19), p('PSA','Psalms',12), p('PHP','Philippians',2)] },
    { day: 88, passages: [p('EXO','Exodus',38), p('JHN','John',20), p('PSA','Psalms',13), p('PHP','Philippians',3)] },
    { day: 89, passages: [p('EXO','Exodus',39), p('JHN','John',21), p('PSA','Psalms',14), p('PHP','Philippians',4)] },
    { day: 90, passages: [p('EXO','Exodus',40), p('MAT','Matthew',1), p('PSA','Psalms',15), p('COL','Colossians',1)] },
  ],
};

// One-Year Genesis to Revelation (sequential reading)
export const GENESIS_TO_REVELATION_PLAN: BibleReadingPlan = {
  id: 'genesis-to-revelation',
  name: 'Genesis to Revelation',
  description: 'Read the entire Bible from cover to cover in one year. 3-4 chapters daily, following canonical order.',
  totalDays: 365,
  estimatedMinutesPerDay: 15,
  dailyReadings: [
    { day: 1, passages: [p('GEN','Genesis',1), p('GEN','Genesis',2), p('GEN','Genesis',3)] },
    { day: 2, passages: [p('GEN','Genesis',4), p('GEN','Genesis',5), p('GEN','Genesis',6)] },
    { day: 3, passages: [p('GEN','Genesis',7), p('GEN','Genesis',8), p('GEN','Genesis',9)] },
    { day: 4, passages: [p('GEN','Genesis',10), p('GEN','Genesis',11), p('GEN','Genesis',12)] },
    { day: 5, passages: [p('GEN','Genesis',13), p('GEN','Genesis',14), p('GEN','Genesis',15)] },
    { day: 6, passages: [p('GEN','Genesis',16), p('GEN','Genesis',17), p('GEN','Genesis',18)] },
    { day: 7, passages: [p('GEN','Genesis',19), p('GEN','Genesis',20), p('GEN','Genesis',21)] },
    { day: 8, passages: [p('GEN','Genesis',22), p('GEN','Genesis',23), p('GEN','Genesis',24)] },
    { day: 9, passages: [p('GEN','Genesis',25), p('GEN','Genesis',26), p('GEN','Genesis',27)] },
    { day: 10, passages: [p('GEN','Genesis',28), p('GEN','Genesis',29), p('GEN','Genesis',30)] },
    { day: 11, passages: [p('GEN','Genesis',31), p('GEN','Genesis',32), p('GEN','Genesis',33)] },
    { day: 12, passages: [p('GEN','Genesis',34), p('GEN','Genesis',35), p('GEN','Genesis',36)] },
    { day: 13, passages: [p('GEN','Genesis',37), p('GEN','Genesis',38), p('GEN','Genesis',39)] },
    { day: 14, passages: [p('GEN','Genesis',40), p('GEN','Genesis',41), p('GEN','Genesis',42)] },
    { day: 15, passages: [p('GEN','Genesis',43), p('GEN','Genesis',44), p('GEN','Genesis',45)] },
    { day: 16, passages: [p('GEN','Genesis',46), p('GEN','Genesis',47), p('GEN','Genesis',48), p('GEN','Genesis',49), p('GEN','Genesis',50)] },
    { day: 17, passages: [p('EXO','Exodus',1), p('EXO','Exodus',2), p('EXO','Exodus',3), p('EXO','Exodus',4)] },
    { day: 18, passages: [p('EXO','Exodus',5), p('EXO','Exodus',6), p('EXO','Exodus',7), p('EXO','Exodus',8)] },
    { day: 19, passages: [p('EXO','Exodus',9), p('EXO','Exodus',10), p('EXO','Exodus',11)] },
    { day: 20, passages: [p('EXO','Exodus',12), p('EXO','Exodus',13), p('EXO','Exodus',14)] },
    { day: 21, passages: [p('EXO','Exodus',15), p('EXO','Exodus',16), p('EXO','Exodus',17), p('EXO','Exodus',18)] },
    { day: 22, passages: [p('EXO','Exodus',19), p('EXO','Exodus',20), p('EXO','Exodus',21)] },
    { day: 23, passages: [p('EXO','Exodus',22), p('EXO','Exodus',23), p('EXO','Exodus',24)] },
    { day: 24, passages: [p('EXO','Exodus',25), p('EXO','Exodus',26), p('EXO','Exodus',27)] },
    { day: 25, passages: [p('EXO','Exodus',28), p('EXO','Exodus',29)] },
    { day: 26, passages: [p('EXO','Exodus',30), p('EXO','Exodus',31), p('EXO','Exodus',32)] },
    { day: 27, passages: [p('EXO','Exodus',33), p('EXO','Exodus',34), p('EXO','Exodus',35)] },
    { day: 28, passages: [p('EXO','Exodus',36), p('EXO','Exodus',37), p('EXO','Exodus',38)] },
    { day: 29, passages: [p('EXO','Exodus',39), p('EXO','Exodus',40), p('LEV','Leviticus',1)] },
    { day: 30, passages: [p('LEV','Leviticus',2), p('LEV','Leviticus',3), p('LEV','Leviticus',4), p('LEV','Leviticus',5)] },
    { day: 31, passages: [p('LEV','Leviticus',6), p('LEV','Leviticus',7), p('LEV','Leviticus',8)] },
    { day: 32, passages: [p('LEV','Leviticus',9), p('LEV','Leviticus',10), p('LEV','Leviticus',11)] },
    { day: 33, passages: [p('LEV','Leviticus',12), p('LEV','Leviticus',13)] },
    { day: 34, passages: [p('LEV','Leviticus',14), p('LEV','Leviticus',15)] },
    { day: 35, passages: [p('LEV','Leviticus',16), p('LEV','Leviticus',17), p('LEV','Leviticus',18)] },
    { day: 36, passages: [p('LEV','Leviticus',19), p('LEV','Leviticus',20), p('LEV','Leviticus',21)] },
    { day: 37, passages: [p('LEV','Leviticus',22), p('LEV','Leviticus',23)] },
    { day: 38, passages: [p('LEV','Leviticus',24), p('LEV','Leviticus',25)] },
    { day: 39, passages: [p('LEV','Leviticus',26), p('LEV','Leviticus',27)] },
    { day: 40, passages: [p('NUM','Numbers',1), p('NUM','Numbers',2), p('NUM','Numbers',3)] },
  ],
};

// New Testament in 30 Days
export const NT_30_DAYS_PLAN: BibleReadingPlan = {
  id: 'nt-30-days',
  name: 'New Testament in 30 Days',
  description: 'Read the entire New Testament in just 30 days. About 9 chapters per day — perfect for a deep NT immersion.',
  totalDays: 30,
  estimatedMinutesPerDay: 45,
  dailyReadings: [
    { day: 1, passages: [p('MAT','Matthew',1), p('MAT','Matthew',2), p('MAT','Matthew',3), p('MAT','Matthew',4), p('MAT','Matthew',5), p('MAT','Matthew',6), p('MAT','Matthew',7), p('MAT','Matthew',8), p('MAT','Matthew',9)] },
    { day: 2, passages: [p('MAT','Matthew',10), p('MAT','Matthew',11), p('MAT','Matthew',12), p('MAT','Matthew',13), p('MAT','Matthew',14), p('MAT','Matthew',15), p('MAT','Matthew',16), p('MAT','Matthew',17)] },
    { day: 3, passages: [p('MAT','Matthew',18), p('MAT','Matthew',19), p('MAT','Matthew',20), p('MAT','Matthew',21), p('MAT','Matthew',22), p('MAT','Matthew',23), p('MAT','Matthew',24), p('MAT','Matthew',25), p('MAT','Matthew',26), p('MAT','Matthew',27), p('MAT','Matthew',28)] },
    { day: 4, passages: [p('MRK','Mark',1), p('MRK','Mark',2), p('MRK','Mark',3), p('MRK','Mark',4), p('MRK','Mark',5), p('MRK','Mark',6), p('MRK','Mark',7), p('MRK','Mark',8)] },
    { day: 5, passages: [p('MRK','Mark',9), p('MRK','Mark',10), p('MRK','Mark',11), p('MRK','Mark',12), p('MRK','Mark',13), p('MRK','Mark',14), p('MRK','Mark',15), p('MRK','Mark',16)] },
    { day: 6, passages: [p('LUK','Luke',1), p('LUK','Luke',2), p('LUK','Luke',3), p('LUK','Luke',4), p('LUK','Luke',5), p('LUK','Luke',6), p('LUK','Luke',7), p('LUK','Luke',8)] },
    { day: 7, passages: [p('LUK','Luke',9), p('LUK','Luke',10), p('LUK','Luke',11), p('LUK','Luke',12), p('LUK','Luke',13), p('LUK','Luke',14), p('LUK','Luke',15)] },
    { day: 8, passages: [p('LUK','Luke',16), p('LUK','Luke',17), p('LUK','Luke',18), p('LUK','Luke',19), p('LUK','Luke',20), p('LUK','Luke',21), p('LUK','Luke',22), p('LUK','Luke',23), p('LUK','Luke',24)] },
    { day: 9, passages: [p('JHN','John',1), p('JHN','John',2), p('JHN','John',3), p('JHN','John',4), p('JHN','John',5), p('JHN','John',6), p('JHN','John',7), p('JHN','John',8)] },
    { day: 10, passages: [p('JHN','John',9), p('JHN','John',10), p('JHN','John',11), p('JHN','John',12), p('JHN','John',13), p('JHN','John',14), p('JHN','John',15), p('JHN','John',16), p('JHN','John',17), p('JHN','John',18), p('JHN','John',19), p('JHN','John',20), p('JHN','John',21)] },
    { day: 11, passages: [p('ACT','Acts',1), p('ACT','Acts',2), p('ACT','Acts',3), p('ACT','Acts',4), p('ACT','Acts',5), p('ACT','Acts',6), p('ACT','Acts',7), p('ACT','Acts',8), p('ACT','Acts',9)] },
    { day: 12, passages: [p('ACT','Acts',10), p('ACT','Acts',11), p('ACT','Acts',12), p('ACT','Acts',13), p('ACT','Acts',14), p('ACT','Acts',15), p('ACT','Acts',16), p('ACT','Acts',17)] },
    { day: 13, passages: [p('ACT','Acts',18), p('ACT','Acts',19), p('ACT','Acts',20), p('ACT','Acts',21), p('ACT','Acts',22), p('ACT','Acts',23), p('ACT','Acts',24), p('ACT','Acts',25), p('ACT','Acts',26), p('ACT','Acts',27), p('ACT','Acts',28)] },
    { day: 14, passages: [p('ROM','Romans',1), p('ROM','Romans',2), p('ROM','Romans',3), p('ROM','Romans',4), p('ROM','Romans',5), p('ROM','Romans',6), p('ROM','Romans',7), p('ROM','Romans',8)] },
    { day: 15, passages: [p('ROM','Romans',9), p('ROM','Romans',10), p('ROM','Romans',11), p('ROM','Romans',12), p('ROM','Romans',13), p('ROM','Romans',14), p('ROM','Romans',15), p('ROM','Romans',16)] },
    { day: 16, passages: [p('1CO','1 Corinthians',1), p('1CO','1 Corinthians',2), p('1CO','1 Corinthians',3), p('1CO','1 Corinthians',4), p('1CO','1 Corinthians',5), p('1CO','1 Corinthians',6), p('1CO','1 Corinthians',7), p('1CO','1 Corinthians',8), p('1CO','1 Corinthians',9)] },
    { day: 17, passages: [p('1CO','1 Corinthians',10), p('1CO','1 Corinthians',11), p('1CO','1 Corinthians',12), p('1CO','1 Corinthians',13), p('1CO','1 Corinthians',14), p('1CO','1 Corinthians',15), p('1CO','1 Corinthians',16), p('2CO','2 Corinthians',1), p('2CO','2 Corinthians',2)] },
    { day: 18, passages: [p('2CO','2 Corinthians',3), p('2CO','2 Corinthians',4), p('2CO','2 Corinthians',5), p('2CO','2 Corinthians',6), p('2CO','2 Corinthians',7), p('2CO','2 Corinthians',8), p('2CO','2 Corinthians',9), p('2CO','2 Corinthians',10), p('2CO','2 Corinthians',11), p('2CO','2 Corinthians',12), p('2CO','2 Corinthians',13)] },
    { day: 19, passages: [p('GAL','Galatians',1), p('GAL','Galatians',2), p('GAL','Galatians',3), p('GAL','Galatians',4), p('GAL','Galatians',5), p('GAL','Galatians',6), p('EPH','Ephesians',1), p('EPH','Ephesians',2), p('EPH','Ephesians',3), p('EPH','Ephesians',4), p('EPH','Ephesians',5), p('EPH','Ephesians',6)] },
    { day: 20, passages: [p('PHP','Philippians',1), p('PHP','Philippians',2), p('PHP','Philippians',3), p('PHP','Philippians',4), p('COL','Colossians',1), p('COL','Colossians',2), p('COL','Colossians',3), p('COL','Colossians',4), p('1TH','1 Thessalonians',1), p('1TH','1 Thessalonians',2), p('1TH','1 Thessalonians',3), p('1TH','1 Thessalonians',4), p('1TH','1 Thessalonians',5)] },
    { day: 21, passages: [p('2TH','2 Thessalonians',1), p('2TH','2 Thessalonians',2), p('2TH','2 Thessalonians',3), p('1TI','1 Timothy',1), p('1TI','1 Timothy',2), p('1TI','1 Timothy',3), p('1TI','1 Timothy',4), p('1TI','1 Timothy',5), p('1TI','1 Timothy',6), p('2TI','2 Timothy',1), p('2TI','2 Timothy',2), p('2TI','2 Timothy',3), p('2TI','2 Timothy',4)] },
    { day: 22, passages: [p('TIT','Titus',1), p('TIT','Titus',2), p('TIT','Titus',3), p('PHM','Philemon',1), p('HEB','Hebrews',1), p('HEB','Hebrews',2), p('HEB','Hebrews',3), p('HEB','Hebrews',4), p('HEB','Hebrews',5), p('HEB','Hebrews',6), p('HEB','Hebrews',7)] },
    { day: 23, passages: [p('HEB','Hebrews',8), p('HEB','Hebrews',9), p('HEB','Hebrews',10), p('HEB','Hebrews',11), p('HEB','Hebrews',12), p('HEB','Hebrews',13), p('JAS','James',1), p('JAS','James',2), p('JAS','James',3), p('JAS','James',4), p('JAS','James',5)] },
    { day: 24, passages: [p('1PE','1 Peter',1), p('1PE','1 Peter',2), p('1PE','1 Peter',3), p('1PE','1 Peter',4), p('1PE','1 Peter',5), p('2PE','2 Peter',1), p('2PE','2 Peter',2), p('2PE','2 Peter',3), p('1JN','1 John',1), p('1JN','1 John',2), p('1JN','1 John',3), p('1JN','1 John',4), p('1JN','1 John',5)] },
    { day: 25, passages: [p('2JN','2 John',1), p('3JN','3 John',1), p('JDE','Jude',1), p('REV','Revelation',1), p('REV','Revelation',2), p('REV','Revelation',3), p('REV','Revelation',4), p('REV','Revelation',5), p('REV','Revelation',6), p('REV','Revelation',7)] },
    { day: 26, passages: [p('REV','Revelation',8), p('REV','Revelation',9), p('REV','Revelation',10), p('REV','Revelation',11), p('REV','Revelation',12), p('REV','Revelation',13), p('REV','Revelation',14), p('REV','Revelation',15), p('REV','Revelation',16), p('REV','Revelation',17), p('REV','Revelation',18), p('REV','Revelation',19), p('REV','Revelation',20), p('REV','Revelation',21), p('REV','Revelation',22)] },
    // Days 27-30: Review / re-read favorite passages
    { day: 27, passages: [p('JHN','John',1), p('JHN','John',3), p('ROM','Romans',8)] },
    { day: 28, passages: [p('1CO','1 Corinthians',13), p('EPH','Ephesians',6), p('PHP','Philippians',4)] },
    { day: 29, passages: [p('HEB','Hebrews',11), p('JAS','James',1), p('1JN','1 John',1)] },
    { day: 30, passages: [p('REV','Revelation',21), p('REV','Revelation',22)] },
  ],
};

// Psalms & Proverbs - 30 day plan
export const PSALMS_PROVERBS_PLAN: BibleReadingPlan = {
  id: 'psalms-proverbs',
  name: 'Psalms & Proverbs',
  description: 'Read through all of Psalms and Proverbs in 30 days — wisdom and worship every morning.',
  totalDays: 30,
  estimatedMinutesPerDay: 12,
  dailyReadings: [
    { day: 1, passages: [p('PSA','Psalms',1), p('PSA','Psalms',2), p('PSA','Psalms',3), p('PSA','Psalms',4), p('PSA','Psalms',5), p('PRO','Proverbs',1)] },
    { day: 2, passages: [p('PSA','Psalms',6), p('PSA','Psalms',7), p('PSA','Psalms',8), p('PSA','Psalms',9), p('PSA','Psalms',10), p('PRO','Proverbs',2)] },
    { day: 3, passages: [p('PSA','Psalms',11), p('PSA','Psalms',12), p('PSA','Psalms',13), p('PSA','Psalms',14), p('PSA','Psalms',15), p('PRO','Proverbs',3)] },
    { day: 4, passages: [p('PSA','Psalms',16), p('PSA','Psalms',17), p('PSA','Psalms',18), p('PRO','Proverbs',4)] },
    { day: 5, passages: [p('PSA','Psalms',19), p('PSA','Psalms',20), p('PSA','Psalms',21), p('PSA','Psalms',22), p('PSA','Psalms',23), p('PRO','Proverbs',5)] },
    { day: 6, passages: [p('PSA','Psalms',24), p('PSA','Psalms',25), p('PSA','Psalms',26), p('PSA','Psalms',27), p('PSA','Psalms',28), p('PRO','Proverbs',6)] },
    { day: 7, passages: [p('PSA','Psalms',29), p('PSA','Psalms',30), p('PSA','Psalms',31), p('PSA','Psalms',32), p('PSA','Psalms',33), p('PRO','Proverbs',7)] },
    { day: 8, passages: [p('PSA','Psalms',34), p('PSA','Psalms',35), p('PSA','Psalms',36), p('PRO','Proverbs',8)] },
    { day: 9, passages: [p('PSA','Psalms',37), p('PSA','Psalms',38), p('PSA','Psalms',39), p('PSA','Psalms',40), p('PSA','Psalms',41), p('PRO','Proverbs',9)] },
    { day: 10, passages: [p('PSA','Psalms',42), p('PSA','Psalms',43), p('PSA','Psalms',44), p('PSA','Psalms',45), p('PSA','Psalms',46), p('PRO','Proverbs',10)] },
    { day: 11, passages: [p('PSA','Psalms',47), p('PSA','Psalms',48), p('PSA','Psalms',49), p('PSA','Psalms',50), p('PRO','Proverbs',11)] },
    { day: 12, passages: [p('PSA','Psalms',51), p('PSA','Psalms',52), p('PSA','Psalms',53), p('PSA','Psalms',54), p('PSA','Psalms',55), p('PRO','Proverbs',12)] },
    { day: 13, passages: [p('PSA','Psalms',56), p('PSA','Psalms',57), p('PSA','Psalms',58), p('PSA','Psalms',59), p('PSA','Psalms',60), p('PRO','Proverbs',13)] },
    { day: 14, passages: [p('PSA','Psalms',61), p('PSA','Psalms',62), p('PSA','Psalms',63), p('PSA','Psalms',64), p('PSA','Psalms',65), p('PRO','Proverbs',14)] },
    { day: 15, passages: [p('PSA','Psalms',66), p('PSA','Psalms',67), p('PSA','Psalms',68), p('PRO','Proverbs',15)] },
    { day: 16, passages: [p('PSA','Psalms',69), p('PSA','Psalms',70), p('PSA','Psalms',71), p('PSA','Psalms',72), p('PRO','Proverbs',16)] },
    { day: 17, passages: [p('PSA','Psalms',73), p('PSA','Psalms',74), p('PSA','Psalms',75), p('PSA','Psalms',76), p('PSA','Psalms',77), p('PRO','Proverbs',17)] },
    { day: 18, passages: [p('PSA','Psalms',78), p('PSA','Psalms',79), p('PSA','Psalms',80), p('PRO','Proverbs',18)] },
    { day: 19, passages: [p('PSA','Psalms',81), p('PSA','Psalms',82), p('PSA','Psalms',83), p('PSA','Psalms',84), p('PSA','Psalms',85), p('PRO','Proverbs',19)] },
    { day: 20, passages: [p('PSA','Psalms',86), p('PSA','Psalms',87), p('PSA','Psalms',88), p('PSA','Psalms',89), p('PRO','Proverbs',20)] },
    { day: 21, passages: [p('PSA','Psalms',90), p('PSA','Psalms',91), p('PSA','Psalms',92), p('PSA','Psalms',93), p('PSA','Psalms',94), p('PRO','Proverbs',21)] },
    { day: 22, passages: [p('PSA','Psalms',95), p('PSA','Psalms',96), p('PSA','Psalms',97), p('PSA','Psalms',98), p('PSA','Psalms',99), p('PSA','Psalms',100), p('PRO','Proverbs',22)] },
    { day: 23, passages: [p('PSA','Psalms',101), p('PSA','Psalms',102), p('PSA','Psalms',103), p('PSA','Psalms',104), p('PRO','Proverbs',23)] },
    { day: 24, passages: [p('PSA','Psalms',105), p('PSA','Psalms',106), p('PRO','Proverbs',24)] },
    { day: 25, passages: [p('PSA','Psalms',107), p('PSA','Psalms',108), p('PSA','Psalms',109), p('PSA','Psalms',110), p('PRO','Proverbs',25)] },
    { day: 26, passages: [p('PSA','Psalms',111), p('PSA','Psalms',112), p('PSA','Psalms',113), p('PSA','Psalms',114), p('PSA','Psalms',115), p('PSA','Psalms',116), p('PSA','Psalms',117), p('PSA','Psalms',118), p('PRO','Proverbs',26)] },
    { day: 27, passages: [p('PSA','Psalms',119,1,88), p('PRO','Proverbs',27)] },
    { day: 28, passages: [p('PSA','Psalms',119,89,176), p('PRO','Proverbs',28)] },
    { day: 29, passages: [p('PSA','Psalms',120), p('PSA','Psalms',121), p('PSA','Psalms',122), p('PSA','Psalms',123), p('PSA','Psalms',124), p('PSA','Psalms',125), p('PSA','Psalms',126), p('PSA','Psalms',127), p('PSA','Psalms',128), p('PSA','Psalms',129), p('PSA','Psalms',130), p('PSA','Psalms',131), p('PSA','Psalms',132), p('PSA','Psalms',133), p('PSA','Psalms',134), p('PRO','Proverbs',29)] },
    { day: 30, passages: [p('PSA','Psalms',135), p('PSA','Psalms',136), p('PSA','Psalms',137), p('PSA','Psalms',138), p('PSA','Psalms',139), p('PSA','Psalms',140), p('PSA','Psalms',141), p('PSA','Psalms',142), p('PSA','Psalms',143), p('PSA','Psalms',144), p('PSA','Psalms',145), p('PSA','Psalms',146), p('PSA','Psalms',147), p('PSA','Psalms',148), p('PSA','Psalms',149), p('PSA','Psalms',150), p('PRO','Proverbs',30), p('PRO','Proverbs',31)] },
  ],
};

// 90-Day Bible reading plan
export const NINETY_DAY_PLAN: BibleReadingPlan = {
  id: '90-day',
  name: '90-Day Bible',
  description: 'Read through the entire Bible in 90 days. A challenging and rewarding plan at about 12-13 chapters per day.',
  totalDays: 90,
  estimatedMinutesPerDay: 50,
  dailyReadings: [
    { day: 1, passages: [p('GEN','Genesis',1), p('GEN','Genesis',2), p('GEN','Genesis',3), p('GEN','Genesis',4), p('GEN','Genesis',5), p('GEN','Genesis',4), p('GEN','Genesis',5), p('GEN','Genesis',6), p('GEN','Genesis',7), p('GEN','Genesis',8), p('GEN','Genesis',9), p('GEN','Genesis',10), p('GEN','Genesis',11), p('GEN','Genesis',12), p('GEN','Genesis',13)] },
    { day: 2, passages: [p('GEN','Genesis',14), p('GEN','Genesis',15), p('GEN','Genesis',16), p('GEN','Genesis',17), p('GEN','Genesis',18), p('GEN','Genesis',19), p('GEN','Genesis',20), p('GEN','Genesis',21), p('GEN','Genesis',22), p('GEN','Genesis',23), p('GEN','Genesis',24), p('GEN','Genesis',25)] },
    { day: 3, passages: [p('GEN','Genesis',26), p('GEN','Genesis',27), p('GEN','Genesis',28), p('GEN','Genesis',29), p('GEN','Genesis',30), p('GEN','Genesis',31), p('GEN','Genesis',32), p('GEN','Genesis',33), p('GEN','Genesis',34), p('GEN','Genesis',35), p('GEN','Genesis',36)] },
    { day: 4, passages: [p('GEN','Genesis',37), p('GEN','Genesis',38), p('GEN','Genesis',39), p('GEN','Genesis',40), p('GEN','Genesis',41), p('GEN','Genesis',42), p('GEN','Genesis',43), p('GEN','Genesis',44), p('GEN','Genesis',45), p('GEN','Genesis',46), p('GEN','Genesis',47), p('GEN','Genesis',48), p('GEN','Genesis',49), p('GEN','Genesis',50)] },
    { day: 5, passages: [p('EXO','Exodus',1), p('EXO','Exodus',2), p('EXO','Exodus',3), p('EXO','Exodus',4), p('EXO','Exodus',5), p('EXO','Exodus',6), p('EXO','Exodus',7), p('EXO','Exodus',8), p('EXO','Exodus',9), p('EXO','Exodus',10), p('EXO','Exodus',11), p('EXO','Exodus',12)] },
    { day: 6, passages: [p('EXO','Exodus',13), p('EXO','Exodus',14), p('EXO','Exodus',15), p('EXO','Exodus',16), p('EXO','Exodus',17), p('EXO','Exodus',18), p('EXO','Exodus',19), p('EXO','Exodus',20), p('EXO','Exodus',21), p('EXO','Exodus',22), p('EXO','Exodus',23), p('EXO','Exodus',24)] },
    { day: 7, passages: [p('EXO','Exodus',25), p('EXO','Exodus',26), p('EXO','Exodus',27), p('EXO','Exodus',28), p('EXO','Exodus',29), p('EXO','Exodus',30), p('EXO','Exodus',31), p('EXO','Exodus',32), p('EXO','Exodus',33), p('EXO','Exodus',34), p('EXO','Exodus',35), p('EXO','Exodus',36), p('EXO','Exodus',37), p('EXO','Exodus',38), p('EXO','Exodus',39), p('EXO','Exodus',40)] },
    { day: 8, passages: [p('LEV','Leviticus',1), p('LEV','Leviticus',2), p('LEV','Leviticus',3), p('LEV','Leviticus',4), p('LEV','Leviticus',5), p('LEV','Leviticus',6), p('LEV','Leviticus',7), p('LEV','Leviticus',8), p('LEV','Leviticus',9), p('LEV','Leviticus',10), p('LEV','Leviticus',11), p('LEV','Leviticus',12), p('LEV','Leviticus',13)] },
    { day: 9, passages: [p('LEV','Leviticus',14), p('LEV','Leviticus',15), p('LEV','Leviticus',16), p('LEV','Leviticus',17), p('LEV','Leviticus',18), p('LEV','Leviticus',19), p('LEV','Leviticus',20), p('LEV','Leviticus',21), p('LEV','Leviticus',22), p('LEV','Leviticus',23), p('LEV','Leviticus',24), p('LEV','Leviticus',25), p('LEV','Leviticus',26), p('LEV','Leviticus',27)] },
    { day: 10, passages: [p('NUM','Numbers',1), p('NUM','Numbers',2), p('NUM','Numbers',3), p('NUM','Numbers',4), p('NUM','Numbers',5), p('NUM','Numbers',6), p('NUM','Numbers',7), p('NUM','Numbers',8), p('NUM','Numbers',9), p('NUM','Numbers',10), p('NUM','Numbers',11), p('NUM','Numbers',12)] },
  ],
};

// Chronological plan (reads Bible in order events occurred)
export const CHRONOLOGICAL_PLAN: BibleReadingPlan = {
  id: 'chronological-one-year',
  name: 'Chronological One-Year',
  description: 'Read the Bible in the order events actually happened — including harmonizing the Gospels and placing Epistles in context.',
  totalDays: 365,
  estimatedMinutesPerDay: 15,
  dailyReadings: [
    { day: 1, passages: [p('GEN','Genesis',1), p('GEN','Genesis',2)] },
    { day: 2, passages: [p('GEN','Genesis',3), p('GEN','Genesis',4)] },
    { day: 3, passages: [p('GEN','Genesis',5), p('GEN','Genesis',6)] },
    { day: 4, passages: [p('GEN','Genesis',7), p('GEN','Genesis',8)] },
    { day: 5, passages: [p('GEN','Genesis',9), p('GEN','Genesis',10)] },
    { day: 6, passages: [p('GEN','Genesis',11), p('JOB','Job',1), p('JOB','Job',2)] },
    { day: 7, passages: [p('JOB','Job',3), p('JOB','Job',4), p('JOB','Job',5), p('JOB','Job',6)] },
    { day: 8, passages: [p('JOB','Job',7), p('JOB','Job',8), p('JOB','Job',9), p('JOB','Job',10)] },
    { day: 9, passages: [p('JOB','Job',11), p('JOB','Job',12), p('JOB','Job',13), p('JOB','Job',14)] },
    { day: 10, passages: [p('JOB','Job',15), p('JOB','Job',16), p('JOB','Job',17), p('JOB','Job',18)] },
    { day: 11, passages: [p('JOB','Job',19), p('JOB','Job',20), p('JOB','Job',21), p('JOB','Job',22)] },
    { day: 12, passages: [p('JOB','Job',23), p('JOB','Job',24), p('JOB','Job',25), p('JOB','Job',26), p('JOB','Job',27)] },
    { day: 13, passages: [p('JOB','Job',28), p('JOB','Job',29), p('JOB','Job',30), p('JOB','Job',31)] },
    { day: 14, passages: [p('JOB','Job',32), p('JOB','Job',33), p('JOB','Job',34), p('JOB','Job',35)] },
    { day: 15, passages: [p('JOB','Job',36), p('JOB','Job',37), p('JOB','Job',38), p('JOB','Job',39)] },
    { day: 16, passages: [p('JOB','Job',40), p('JOB','Job',41), p('JOB','Job',42), p('GEN','Genesis',12)] },
    { day: 17, passages: [p('GEN','Genesis',13), p('GEN','Genesis',14), p('GEN','Genesis',15), p('GEN','Genesis',16)] },
    { day: 18, passages: [p('GEN','Genesis',17), p('GEN','Genesis',18), p('GEN','Genesis',19)] },
    { day: 19, passages: [p('GEN','Genesis',20), p('GEN','Genesis',21), p('GEN','Genesis',22)] },
    { day: 20, passages: [p('GEN','Genesis',23), p('GEN','Genesis',24)] },
    { day: 21, passages: [p('GEN','Genesis',25), p('GEN','Genesis',26)] },
    { day: 22, passages: [p('GEN','Genesis',27), p('GEN','Genesis',28)] },
    { day: 23, passages: [p('GEN','Genesis',29), p('GEN','Genesis',30)] },
    { day: 24, passages: [p('GEN','Genesis',31), p('GEN','Genesis',32)] },
    { day: 25, passages: [p('GEN','Genesis',33), p('GEN','Genesis',34), p('GEN','Genesis',35)] },
    { day: 26, passages: [p('GEN','Genesis',36), p('GEN','Genesis',37), p('GEN','Genesis',38)] },
    { day: 27, passages: [p('GEN','Genesis',39), p('GEN','Genesis',40), p('GEN','Genesis',41)] },
    { day: 28, passages: [p('GEN','Genesis',42), p('GEN','Genesis',43), p('GEN','Genesis',44)] },
    { day: 29, passages: [p('GEN','Genesis',45), p('GEN','Genesis',46), p('GEN','Genesis',47)] },
    { day: 30, passages: [p('GEN','Genesis',48), p('GEN','Genesis',49), p('GEN','Genesis',50)] },
    { day: 31, passages: [p('EXO','Exodus',1), p('EXO','Exodus',2), p('EXO','Exodus',3)] },
    { day: 32, passages: [p('EXO','Exodus',4), p('EXO','Exodus',5), p('EXO','Exodus',6), p('EXO','Exodus',7)] },
    { day: 33, passages: [p('EXO','Exodus',8), p('EXO','Exodus',9), p('EXO','Exodus',10)] },
    { day: 34, passages: [p('EXO','Exodus',11), p('EXO','Exodus',12), p('EXO','Exodus',13)] },
    { day: 35, passages: [p('EXO','Exodus',14), p('EXO','Exodus',15), p('EXO','Exodus',16)] },
    { day: 36, passages: [p('EXO','Exodus',17), p('EXO','Exodus',18), p('EXO','Exodus',19), p('EXO','Exodus',20)] },
    { day: 37, passages: [p('EXO','Exodus',21), p('EXO','Exodus',22), p('EXO','Exodus',23), p('EXO','Exodus',24)] },
    { day: 38, passages: [p('EXO','Exodus',25), p('EXO','Exodus',26), p('EXO','Exodus',27), p('EXO','Exodus',28)] },
    { day: 39, passages: [p('EXO','Exodus',29), p('EXO','Exodus',30), p('EXO','Exodus',31)] },
    { day: 40, passages: [p('EXO','Exodus',32), p('EXO','Exodus',33), p('EXO','Exodus',34)] },
  ],
};

// OT One-Year Plan
export const OT_ONE_YEAR_PLAN: BibleReadingPlan = {
  id: 'ot-one-year',
  name: 'Old Testament in a Year',
  description: 'A focused journey through the entire Old Testament in one year, with about 2-3 chapters per day.',
  totalDays: 365,
  estimatedMinutesPerDay: 10,
  dailyReadings: [
    { day: 1, passages: [p('GEN','Genesis',1), p('GEN','Genesis',2)] },
    { day: 2, passages: [p('GEN','Genesis',3), p('GEN','Genesis',4)] },
    { day: 3, passages: [p('GEN','Genesis',5), p('GEN','Genesis',6)] },
    { day: 4, passages: [p('GEN','Genesis',7), p('GEN','Genesis',8)] },
    { day: 5, passages: [p('GEN','Genesis',9), p('GEN','Genesis',10)] },
    { day: 6, passages: [p('GEN','Genesis',11), p('GEN','Genesis',12)] },
    { day: 7, passages: [p('GEN','Genesis',13), p('GEN','Genesis',14)] },
    { day: 8, passages: [p('GEN','Genesis',15), p('GEN','Genesis',16)] },
    { day: 9, passages: [p('GEN','Genesis',17), p('GEN','Genesis',18)] },
    { day: 10, passages: [p('GEN','Genesis',19), p('GEN','Genesis',20)] },
    { day: 11, passages: [p('GEN','Genesis',21), p('GEN','Genesis',22)] },
    { day: 12, passages: [p('GEN','Genesis',23), p('GEN','Genesis',24)] },
    { day: 13, passages: [p('GEN','Genesis',25), p('GEN','Genesis',26)] },
    { day: 14, passages: [p('GEN','Genesis',27), p('GEN','Genesis',28)] },
    { day: 15, passages: [p('GEN','Genesis',29), p('GEN','Genesis',30)] },
    { day: 16, passages: [p('GEN','Genesis',31), p('GEN','Genesis',32)] },
    { day: 17, passages: [p('GEN','Genesis',33), p('GEN','Genesis',34)] },
    { day: 18, passages: [p('GEN','Genesis',35), p('GEN','Genesis',36)] },
    { day: 19, passages: [p('GEN','Genesis',37), p('GEN','Genesis',38)] },
    { day: 20, passages: [p('GEN','Genesis',39), p('GEN','Genesis',40)] },
    { day: 21, passages: [p('GEN','Genesis',41), p('GEN','Genesis',42)] },
    { day: 22, passages: [p('GEN','Genesis',43), p('GEN','Genesis',44)] },
    { day: 23, passages: [p('GEN','Genesis',45), p('GEN','Genesis',46)] },
    { day: 24, passages: [p('GEN','Genesis',47), p('GEN','Genesis',48)] },
    { day: 25, passages: [p('GEN','Genesis',49), p('GEN','Genesis',50)] },
    { day: 26, passages: [p('EXO','Exodus',1), p('EXO','Exodus',2)] },
    { day: 27, passages: [p('EXO','Exodus',3), p('EXO','Exodus',4)] },
    { day: 28, passages: [p('EXO','Exodus',5), p('EXO','Exodus',6)] },
    { day: 29, passages: [p('EXO','Exodus',7), p('EXO','Exodus',8)] },
    { day: 30, passages: [p('EXO','Exodus',9), p('EXO','Exodus',10)] },
  ],
};

export const ALL_PLANS: BibleReadingPlan[] = [
  MCHEYNE_PLAN,
  GENESIS_TO_REVELATION_PLAN,
  CHRONOLOGICAL_PLAN,
  NINETY_DAY_PLAN,
  NT_30_DAYS_PLAN,
  PSALMS_PROVERBS_PLAN,
  OT_ONE_YEAR_PLAN,
];

export function getPlanById(planId: string): BibleReadingPlan | undefined {
  return ALL_PLANS.find(plan => plan.id === planId);
}

export function getDayReadings(planId: string, dayNumber: number) {
  const plan = getPlanById(planId);
  if (!plan) return null;
  return plan.dailyReadings.find(r => r.day === dayNumber) ?? null;
}
